{{- if .Values.appstore.postgresdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalyst-go-app.secretName" . }}-postgresdb
  labels:
    {{- include "catalyst-go-app.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.appstore.postgresdb.url | b64enc | quote}} 
{{- end }}
{{- if .Values.appstore.cockroachdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalyst-go-app.secretName" . }}-cockroachdb
  labels:
    {{- include "catalyst-go-app.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.appstore.cockroachdb.url | b64enc | quote }} 
{{- end }}
